SQL> ALTER SESSION SET CONTAINER=wed_27249_berenice_stolenVehicleRecovery_db;

Session altered.

SQL> CREATE TABLE Owner (
  2      Owner_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  3      Full_Name VARCHAR2(100) NOT NULL,
  4      Phone VARCHAR2(15),
  5      Email VARCHAR2(50) UNIQUE
  6  );

Table created.

SQL> CREATE TABLE Vehicle (
  2      Vehicle_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  3      License_Plate VARCHAR2(10) NOT NULL UNIQUE,
  4      Model VARCHAR2(50),
  5      Color VARCHAR2(20),
  6      Owner_ID NUMBER NOT NULL,
  7      CONSTRAINT fk_vehicle_owner FOREIGN KEY (Owner_ID) REFERENCES Owner(Owner_ID)
  8  );

Table created.

SQL> CREATE TABLE Theft_Report (
  2  Report_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  3      Vehicle_ID NUMBER NOT NULL,
  4      Report_Date DATE DEFAULT SYSDATE NOT NULL,
  5      Status VARCHAR2(20) DEFAULT 'Pending' CHECK (Status IN ('Pending','Recovered','Rejected')),
  6      CONSTRAINT fk_report_vehicle FOREIGN KEY (Vehicle_ID) REFERENCES Vehicle(Vehicle_ID)
  7  );

Table created.

SQL> CREATE TABLE GPS_Tracker (
  2      Tracker_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  3      Vehicle_ID NUMBER NOT NULL,
  4      Model VARCHAR2(50),
  5      Installed_Date DATE DEFAULT SYSDATE,
  6      Status VARCHAR2(20) DEFAULT 'Active' CHECK (Status IN ('Active','Inactive')),
  7      CONSTRAINT fk_tracker_vehicle FOREIGN KEY (Vehicle_ID) REFERENCES Vehicle(Vehicle_ID)
  8  );

Table created.

SQL> CREATE TABLE Location_Log (
  2      Log_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  3      Tracker_ID NUMBER NOT NULL,
  4      Log_Time TIMESTAMP DEFAULT SYSTIMESTAMP,
  5      Latitude NUMBER(10,6),
  6      Longitude NUMBER(10,6),
  7      Accuracy_Meters NUMBER(5),
  8      CONSTRAINT fk_log_tracker FOREIGN KEY (Tracker_ID) REFERENCES GPS_Tracker(Tracker_ID)
  9  );

Table created.

SQL> CREATE TABLE Alert (
  2      Alert_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  3      Report_ID NUMBER NOT NULL,
  4      Alert_Time TIMESTAMP DEFAULT SYSTIMESTAMP,
  5      Alert_Type VARCHAR2(50) CHECK (Alert_Type IN ('SMS','Email','Push')),
  6      Message VARCHAR2(200),
  7      Status VARCHAR2(20) DEFAULT 'Sent' CHECK (Status IN ('Sent','Failed','Pending')),
  8      CONSTRAINT fk_alert_report FOREIGN KEY (Report_ID) REFERENCES Theft_Report(Report_ID)
  9  );

Table created.
