SQL> SET SERVEROUTPUT ON
SQL> CREATE TABLE error_log (
  2      log_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  3      occurred_at  TIMESTAMP DEFAULT SYSTIMESTAMP,
  4      component    VARCHAR2(100),
  5      err_code     NUMBER,
  6      err_msg      VARCHAR2(4000),
  7      context_info VARCHAR2(4000)
  8  );

Table created.

SQL> CREATE OR REPLACE PROCEDURE log_error(
  2      p_component    IN VARCHAR2,
  3      p_err_code     IN NUMBER,
  4      p_err_msg      IN VARCHAR2,
  5      p_context_info IN VARCHAR2
  6  ) IS
  7  BEGIN
  8      INSERT INTO error_log (component, err_code, err_msg, context_info)
  9      VALUES (p_component, p_err_code, p_err_msg, p_context_info);
 10      COMMIT;
 11  END log_error;
 12  /

Procedure created.

SQL> CREATE OR REPLACE PROCEDURE add_owner(
  2      p_full_name  IN  VARCHAR2,
  3      p_phone      IN  VARCHAR2,
  4      p_email      IN  VARCHAR2,
  5      p_address    IN  VARCHAR2,
  6      p_owner_id   OUT NUMBER
  7  ) IS
  8  BEGIN
  9      SELECT NVL(MAX(Owner_ID),0) + 1 INTO p_owner_id FROM Owner;
 10
 11      INSERT INTO Owner (Owner_ID, Full_Name, Phone, Email, Owner_Address)
 12      VALUES (p_owner_id, p_full_name, p_phone, p_email, p_address);
 13
 14      COMMIT;
 15
 16  EXCEPTION
 17      WHEN OTHERS THEN
 18          log_error('add_owner', SQLCODE, SUBSTR(SQLERRM,1,2000),
 19                    'p_full_name='||p_full_name||' p_email='||p_email);
 20          RAISE;
 21  END add_owner;
 22  /

Procedure created.

SQL> CREATE OR REPLACE PROCEDURE update_vehicle_status(
  2    p_vehicle_id IN NUMBER,
  3    p_status     IN VARCHAR2
  4  ) IS
  5    e_not_found EXCEPTION;
  6  BEGIN
  7    UPDATE Vehicle
  8    SET Status = p_status
  9    WHERE Vehicle_ID = p_vehicle_id;
 10
 11    IF SQL%ROWCOUNT = 0 THEN
 12      RAISE e_not_found;
 13    END IF;
 14
 15    COMMIT;
 16  EXCEPTION
 17    WHEN e_not_found THEN
 18      log_error('update_vehicle_status', -1, 'Vehicle not found', 'vehicle='||p_vehicle_id);
 19      RAISE_APPLICATION_ERROR(-20001, 'Vehicle not found: '||p_vehicle_id);
 20    WHEN OTHERS THEN
 21      log_error('update_vehicle_status', SQLCODE, SUBSTR(SQLERRM,1,2000), 'vehicle='||p_vehicle_id);
 22      RAISE;
 23  END update_vehicle_status;
 24  /

Procedure created.

SQL> CREATE OR REPLACE PROCEDURE create_theft_report(
  2    p_vehicle_id IN NUMBER,
  3    p_status     IN VARCHAR2,
  4    p_report_id  IN OUT NUMBER
  5  ) IS
  6  BEGIN
  7    IF p_report_id IS NULL OR p_report_id = 0 THEN
  8      SELECT NVL(MAX(REPORT_ID),0) + 1 INTO p_report_id FROM Theft_Report;
  9      INSERT INTO Theft_Report (REPORT_ID, VEHICLE_ID, REPORT_DATE, STATUS)
 10        VALUES (p_report_id, p_vehicle_id, SYSTIMESTAMP, p_status);
 11    ELSE
 12      -- update existing
 13      UPDATE Theft_Report
 14      SET VEHICLE_ID = p_vehicle_id,
 15          REPORT_DATE = SYSTIMESTAMP,
 16          STATUS = p_status
 17      WHERE REPORT_ID = p_report_id;
 18
 19      IF SQL%ROWCOUNT = 0 THEN
 20        RAISE_APPLICATION_ERROR(-20002, 'Report not found for update: '||p_report_id);
 21      END IF;
 22    END IF;
 23
 24    COMMIT;
 25  EXCEPTION
 26    WHEN OTHERS THEN
 27      log_error('create_theft_report', SQLCODE, SUBSTR(SQLERRM,1,2000),
 28                'p_report_id='||NVL(TO_CHAR(p_report_id),'NULL')||' p_vehicle='||p_vehicle_id);
 29      RAISE;
 30  END create_theft_report;
 31  /

Procedure created.

SQL> CREATE OR REPLACE PROCEDURE resolve_alert(
  2    p_alert_id    IN  NUMBER,
  3    p_new_resolved IN CHAR,
  4    p_old_resolved OUT CHAR
  5  ) IS
  6  BEGIN
  7    SELECT Resolved INTO p_old_resolved FROM Alert WHERE Alert_ID = p_alert_id;
  8
  9    UPDATE Alert
 10    SET Resolved = p_new_resolved
 11    WHERE Alert_ID = p_alert_id;
 12
 13    IF SQL%ROWCOUNT = 0 THEN
 14      RAISE_APPLICATION_ERROR(-20003,'Alert not found: '||p_alert_id);
 15    END IF;
 16
 17    COMMIT;
 18  EXCEPTION
 19    WHEN NO_DATA_FOUND THEN
 20      log_error('resolve_alert', -1, 'Alert not found', 'alert='||p_alert_id);
 21      RAISE_APPLICATION_ERROR(-20003,'Alert not found: '||p_alert_id);
 22    WHEN OTHERS THEN
 23      log_error('resolve_alert', SQLCODE, SUBSTR(SQLERRM,1,2000), 'alert='||p_alert_id);
 24      RAISE;
 25  END resolve_alert;
 26  /

Procedure created.

