SQL> CREATE TABLE holidays (
  2      holiday_date DATE PRIMARY KEY,
  3      description VARCHAR2(100)
  4  );

Table created.

SQL> INSERT INTO holidays VALUES (DATE '2025-12-25', 'Christmas');

1 row created.

SQL> INSERT INTO holidays VALUES (DATE '2025-12-31', 'New Year Eve');

1 row created.

SQL> COMMIT;

Commit complete.

SQL> CREATE TABLE audit_log (
  2      log_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  3      action_time   TIMESTAMP DEFAULT SYSTIMESTAMP,
  4      user_name     VARCHAR2(30),
  5      operation     VARCHAR2(10),
  6      table_name    VARCHAR2(30),
  7      status        VARCHAR2(10),  -- ALLOWED / DENIED
  8      remarks       VARCHAR2(4000)
  9  );

Table created.

SQL> CREATE OR REPLACE PROCEDURE log_audit(
  2      p_event IN VARCHAR2,
  3      p_table IN VARCHAR2,
  4      p_status IN VARCHAR2,
  5      p_message IN VARCHAR2
  6  ) IS
  7  BEGIN
  8      INSERT INTO audit_log(user_name, table_name, operation, status, remarks, action_time)
  9      VALUES (USER, p_table, p_event, p_status, p_message, SYSTIMESTAMP);
 10
 11      COMMIT;
 12  END;
 13  /

Procedure created.

SQL> CREATE OR REPLACE FUNCTION check_dml_allowed RETURN BOOLEAN IS
  2      v_today DATE := TRUNC(SYSDATE);
  3      v_count NUMBER;
  4  BEGIN
  5      -- Check if today is a holiday
  6      SELECT COUNT(*) INTO v_count FROM holidays WHERE holiday_date = v_today;
  7      IF v_count > 0 THEN
  8          RETURN FALSE;
  9      END IF;
 10
 11      -- Check if today is weekday (Mon-Fri)
 12      IF TO_CHAR(v_today,'DY','NLS_DATE_LANGUAGE=ENGLISH') IN ('MON','TUE','WED','THU','FRI') THEN
 13          RETURN FALSE;
 14      END IF;
 15
 16      RETURN TRUE; -- weekend and not holiday
 17  END check_dml_allowed;
 18  /

Function created.

SQL> CREATE OR REPLACE FUNCTION check_dml_allowed(p_date DATE)
  2  RETURN BOOLEAN
  3  IS
  4      v_day VARCHAR2(10);
  5      v_holiday NUMBER;
  6  BEGIN
  7      -- Check day of week
  8      v_day := TO_CHAR(p_date, 'DY', 'NLS_DATE_LANGUAGE=ENGLISH');
  9
 10      -- Weekday = disallowed
 11      IF v_day NOT IN ('SAT', 'SUN') THEN
 12          RETURN FALSE;
 13      END IF;
 14
 15      -- Check holiday table
 16      SELECT COUNT(*) INTO v_holiday
 17      FROM holidays
 18      WHERE holiday_date = TRUNC(p_date);
 19
 20      IF v_holiday > 0 THEN
 21          RETURN FALSE;
 22      END IF;
 23
 24      RETURN TRUE;
 25  END;
 26  /

Function created.

SQL> CREATE OR REPLACE TRIGGER trg_alert_dml
  2  BEFORE INSERT OR UPDATE OR DELETE ON Alert
  3  FOR EACH ROW
  4  DECLARE
  5      v_allowed BOOLEAN;
  6  BEGIN
  7      -- Check if DML is allowed (weekends only, excluding upcoming public holidays)
  8      v_allowed := check_dml_allowed(SYSDATE);
  9
 10      IF NOT v_allowed THEN
 11          -- Log denied attempt
 12          log_audit(
 13              ORA_SYSEVENT,       -- INSERT, UPDATE, DELETE
 14              'Alert',
 15              'DENIED',
 16              'Operation not allowed on weekdays or holidays'
 17          );
 18
 19          -- Stop operation
 20          RAISE_APPLICATION_ERROR(-20051, 'Processing alerts not allowed on weekdays or holidays');
 21      ELSE
 22          -- Log allowed attempt
 23          log_audit(
 24              ORA_SYSEVENT,
 25              'Alert',
 26              'ALLOWED',
 27              'Operation permitted'
 28          );
 29      END IF;
 30  END;
 31  /

Trigger created.

SQL> CREATE OR REPLACE TRIGGER trg_alert_compound
  2  FOR INSERT OR UPDATE OR DELETE ON alerts
  3  COMPOUND TRIGGER
  4
  5      -- A collection to store audit info for all rows
  6      TYPE t_audit IS TABLE OF alert_audit%ROWTYPE;
  7      audit_entries t_audit := t_audit();
  8
  9      -- Before each row (validation)
 10      BEFORE EACH ROW IS
 11          v_count NUMBER;
 12      BEGIN
 13          -- 1. Block weekend & holiday operations
 14          IF TO_CHAR(SYSDATE, 'DY', 'NLS_DATE_LANGUAGE=ENGLISH') IN ('SAT','SUN')
 15             OR is_holiday(SYSDATE) = 1 THEN
 16              RAISE_APPLICATION_ERROR(-20001,
 17                  'DML not allowed on weekends or holidays.');
 18          END IF;
 19
 20          -- 2. Prevent duplicate active alerts
 21          IF INSERTING THEN
 22              SELECT COUNT(*) INTO v_count
 23              FROM alerts
 24              WHERE vehicle_id = :NEW.vehicle_id
 25                AND status = 'ACTIVE';
 26
 27              IF v_count > 0 THEN
 28                  RAISE_APPLICATION_ERROR(-20002,
 29                      'Vehicle already has an active alert.');
 30              END IF;
 31          END IF;
 32
 33      END BEFORE EACH ROW;
 34
 35      -- After each row (collect info for audit)
 36      AFTER EACH ROW IS
 37          v_action VARCHAR2(20);
 38      BEGIN
 39          IF INSERTING THEN v_action := 'INSERT';
 40          ELSIF UPDATING THEN v_action := 'UPDATE';
 41          ELSIF DELETING THEN v_action := 'DELETE';
 42          END IF;
 43
 44          audit_entries.EXTEND;
 45          audit_entries(audit_entries.LAST).alert_id := NVL(:NEW.alert_id, :OLD.alert_id);
 46          audit_entries(audit_entries.LAST).action_type := v_action;
 47          audit_entries(audit_entries.LAST).username := USER;
 48          audit_entries(audit_entries.LAST).action_date := SYSDATE;
 49      END AFTER EACH ROW;
 50
 51      -- After statement (insert collected audit rows)
 52      AFTER STATEMENT IS
 53      BEGIN
 54          FOR i IN 1 .. audit_entries.COUNT LOOP
 55              INSERT INTO alert_audit(audit_id, alert_id, action_type, action_date, username)
 56              VALUES (
 57                  alert_audit_seq.NEXTVAL,
 58                  audit_entries(i).alert_id,
 59                  audit_entries(i).action_type,
 60                  audit_entries(i).action_date,
 61                  audit_entries(i).username
 62              );
 63          END LOOP;
 64      END AFTER STATEMENT;
 65
 66  END trg_alert_compound;
 67  /
Enter value for holiday:
old  13:         -- 1. Block weekend & holiday operations
new  13:         -- 1. Block weekend  operations
FOR INSERT OR UPDATE OR DELETE ON alerts
                                  *
ERROR at line 2:
ORA-00942: table or view does not exist


SQL> SET DEFINE OFF;
SQL> CREATE TABLE alert_audit (
  2      audit_id       NUMBER PRIMARY KEY,
  3      alert_id       NUMBER,
  4      action_type    VARCHAR2(20),
  5      action_date    DATE,
  6      username       VARCHAR2(30)
  7  );

Table created.

SQL> CREATE SEQUENCE alert_audit_seq START WITH 1 INCREMENT BY 1;

Sequence created.

SQL> CREATE OR REPLACE FUNCTION is_holiday(p_date IN DATE) RETURN NUMBER IS
  2      v_count NUMBER;
  3  BEGIN
  4      SELECT COUNT(*) INTO v_count
  5      FROM holidays
  6      WHERE holiday_date = TRUNC(p_date);
  7
  8      IF v_count > 0 THEN
  9          RETURN 1;
 10      ELSE
 11          RETURN 0;
 12      END IF;
 13  END;
 14  /

Function created.

SQL> CREATE OR REPLACE TRIGGER trg_alert_compound
  2  FOR INSERT OR UPDATE OR DELETE ON alert
  3  COMPOUND TRIGGER
  4
  5      -- Collection to store audit info for allowed rows
  6      TYPE t_audit IS TABLE OF alert_audit%ROWTYPE;
  7      audit_entries t_audit := t_audit();
  8
  9      -- Before each row: validation and DENIED logging
 10      BEFORE EACH ROW IS
 11          v_count NUMBER;
 12      BEGIN
 13          -- Block weekdays
 14          IF TO_CHAR(SYSDATE, 'DY', 'NLS_DATE_LANGUAGE=ENGLISH')
 15             IN ('MON','TUE','WED','THU','FRI') OR is_holiday(SYSDATE) = 1 THEN
 16              -- Log DENIED immediately
 17              INSERT INTO alert_audit(audit_id, alert_id, action_type, action_date, username)
 18              VALUES (alert_audit_seq.NEXTVAL,
 19                      NVL(:NEW.alert_id, :OLD.alert_id),
 20                      ORA_SYSEVENT,
 21                      SYSDATE,
 22                      USER);
 23
 24              RAISE_APPLICATION_ERROR(-20001, 'DML not allowed on weekdays or holidays.');
 25          END IF;
 26
 27          -- Prevent duplicate active alerts
 28          IF INSERTING THEN
 29              SELECT COUNT(*) INTO v_count
 30              FROM alert
 31              WHERE vehicle_id = :NEW.vehicle_id
 32                AND status = 'ACTIVE';
 33
 34              IF v_count > 0 THEN
 35                  -- Log DENIED attempt
 36                  INSERT INTO alert_audit(audit_id, alert_id, action_type, action_date, username)
 37                  VALUES (alert_audit_seq.NEXTVAL,
 38                          :NEW.alert_id,
 39                          'INSERT',
 40                          SYSDATE,
 41                          USER);
 42
 43                  RAISE_APPLICATION_ERROR(-20002, 'Vehicle already has an active alert.');
 44              END IF;
 45          END IF;
 46      END BEFORE EACH ROW;
 47
 48      -- After each row: collect info for allowed operations
 49      AFTER EACH ROW IS
 50          v_action VARCHAR2(20);
 51      BEGIN
 52          IF INSERTING THEN v_action := 'INSERT';
 53          ELSIF UPDATING THEN v_action := 'UPDATE';
 54          ELSIF DELETING THEN v_action := 'DELETE';
 55          END IF;
 56
 57          audit_entries.EXTEND;
 58          audit_entries(audit_entries.LAST).alert_id := NVL(:NEW.alert_id, :OLD.alert_id);
 59          audit_entries(audit_entries.LAST).action_type := v_action;
 60          audit_entries(audit_entries.LAST).action_date := SYSDATE;
 61          audit_entries(audit_entries.LAST).username := USER;
 62      END AFTER EACH ROW;
 63
 64      -- After statement: insert collected audit rows
 65      AFTER STATEMENT IS
 66      BEGIN
 67          FOR i IN 1 .. audit_entries.COUNT LOOP
 68              INSERT INTO alert_audit(audit_id, alert_id, action_type, action_date, username)
 69              VALUES (alert_audit_seq.NEXTVAL,
 70                      audit_entries(i).alert_id,
 71                      audit_entries(i).action_type,
 72                      audit_entries(i).action_date,
 73                      audit_entries(i).username);
 74          END LOOP;
 75      END AFTER STATEMENT;
 76
 77  END trg_alert_compound;
 78  /

Trigger created.

